FROM node:11.9.0-alpine

RUN mkdir -p /home/node/app
RUN mkdir -p /home/node/app/node_modules 
RUN chown -R node:node /home/node/app

WORKDIR /home/node/app

#WORKDIR /usr/src/app/contaSoftFrontEnd/UIcontaSoft

COPY files/. .

RUN npm install --only=production

RUN npm install webpack webpack-cli -g

 Build the app
#RUN npm build

#EXPOSE 3000/tcp

#CMD npm start run
